### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by jdhao** [XXiaoA/nvimrc#3]
the link given in [this section](https://github.com/XXiaoA/nvimrc#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) is broken. Apparently, you have changed your dir structure, but do not update the readme.

**Comment by XXiaoA** [comment]
Yeah, I'm too lazy to update my readme. 🤣 I'll update it if I ~~have interest~~ get free one day.
BTW, I've written the [notice](https://github.com/XXiaoA/nvimrc#version)  for a long time

**Comment by jdhao** [comment]
okay, then ...
